In [1]:
# Import the random module.
import random

In [3]:
random.randint(-90, 90)

-33

In [4]:
random.random()

0.32479127467917446

In [5]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1
    

In [6]:
print (latitudes)

[61.37946910548047, -43.91529316920175, -73.4912679511176, -6.692810572120093, 26.18725650508066, -20.222770053223066, 21.909887231090195, 24.73833522485329, -22.960055908400236, 65.96707996699777]


In [7]:
random.randrange(-90, 90, step=1)

-43

In [8]:
random.randrange(-90, 90, step=3)

48

In [9]:
random.uniform(-90, 90)

1.4448145102547727

In [10]:
# Import the NumPy module.
import numpy as np

In [14]:
np.random.uniform(-90.000, 90.000)

53.16492638258532

In [15]:
np.random.uniform(low=-90, high=90)

-14.878310497356736

In [18]:
np.random.uniform(-90.000, 90.000, size=50)

array([ 86.65841714,  21.08925421,  27.52823183, -81.86529612,
        68.45421778,  40.54994823,  17.50698458,  83.29503241,
        61.86748583,  38.79638891,  87.78683877, -57.14606822,
        32.09485733,  -6.23519281, -66.94148116,  27.28572453,
        -9.88360814, -65.38148193,  40.53924524, -81.8375916 ,
       -41.77241351, -50.22225926,  42.47682087, -33.47334117,
        43.07971671,  41.5043202 , -76.44851574,  58.3819248 ,
       -19.11410222, -74.69162238,  -6.77594008,  -3.89375003,
         4.90979901, -81.53315456,  -9.90181013,  44.88496234,
       -28.84856882,   3.78775573,  18.62932949,  41.16083225,
        26.94902284,   4.9682511 ,  63.64222443, -54.35919049,
       -39.46030447,  72.06741109, -68.96256834,  -7.77863104,
        82.2920975 ,  81.78727177])

In [19]:
# Import timeit.
import timeit

In [20]:
np.random.uniform(-90.000, 90.000, size=1500)

array([-28.4910573 , -26.11772018,  79.47290585, ...,  89.19998732,
       -35.20249719,  73.86828597])

In [21]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

28.3 µs ± 10.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [22]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

2.85 ms ± 963 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 62.12891029, -50.031113  , -76.85768305, ...,  60.52912577,
       -74.59290631,  57.09439075])